-- QtLucide - Lucide Icons for Qt Applications
-- XMake build configuration equivalent to CMakeLists.txt

-- Project configuration
set_project("QtLucide")
set_version("1.0.0")
set_languages("cxx17")

-- Detect if QtLucide is being built as a submodule
local is_subproject = os.scriptdir() ~= os.projectdir()

-- Build options - default to false when used as subproject
local default_examples = not is_subproject
local default_tests = not is_subproject

option("examples")
    set_default(default_examples)
    set_description("Build QtLucide examples")
    set_showmenu(true)
option_end()

option("tests")
    set_default(default_tests)
    set_description("Build QtLucide tests")
    set_showmenu(true)
option_end()

option("install")
    set_default(not is_subproject)
    set_description("Install QtLucide files")
    set_showmenu(true)
option_end()

-- Qt6 SDK path option (auto-detect or user-specified)
option("qt_dir")
    set_default("")
    set_description("Qt6 SDK directory (auto-detected if not specified)")
    set_showmenu(true)
option_end()

-- Add Qt6 package requirement
add_rules("mode.debug", "mode.release")

-- Python will be checked during build process

-- Custom rule for resource generation
rule("generate_resources")
    set_extensions(".svg")
    on_buildcmd_file(function (target, batchcmds, sourcefile, opt)
        -- This rule will be triggered when SVG files change
        local python_cmd = "python"
        if os.host() == "windows" then
            python_cmd = "python.exe"
        end
        local build_script = path.join(os.projectdir(), "tools", "build_resources.py")
        local project_dir = os.projectdir()

        -- Add command to generate resources
        batchcmds:show_progress(opt.progress, "Generating QtLucide resources...")
        batchcmds:vrunv(python_cmd, {build_script, project_dir})
    end)
rule_end()

-- Helper function to configure Qt6 for a target
function configure_qt6(target_obj, modules)
    target_obj:add("rules", "qt.moc")
    target_obj:add("rules", "qt.qrc")

    -- Use xmake's built-in Qt detection
    for _, mod in ipairs(modules) do
        target_obj:add("frameworks", "Qt" .. mod)
    end
end

-- QtLucide library target
target("QtLucide")
    set_kind("static")  -- Static library for easier linking

    -- Use xmake's built-in Qt support
    add_rules("qt.static")
    add_frameworks("QtCore", "QtGui", "QtWidgets", "QtSvg")

    -- Source files
    add_files("src/QtLucide.cpp")
    add_files("src/QtLucideIconEngine.cpp")
    add_files("src/QtLucideIconPainter.cpp")

    -- Header files that need MOC processing
    add_files("include/QtLucide/QtLucide.h")

    -- Other header files
    add_headerfiles("include/QtLucide/QtLucideIconEngine.h")
    add_headerfiles("include/QtLucide/QtLucideIconPainter.h")
    add_headerfiles("include/QtLucide/QtLucideEnums.h")
    add_headerfiles("include/QtLucide/QtLucideStrings.h")
    add_includedirs("include", {public = true})

    -- Add generated QRC file
    add_files("resources/icons/lucide_icons.qrc")

    -- Set target properties
    set_basename("QtLucide")

    -- Export symbols for shared library
    if is_plat("windows", "mingw") then
        add_defines("QTLUCIDE_LIBRARY")
    end

    -- Installation (only when not used as subproject or explicitly requested)
    if has_config("install") then
        on_install(function (target)
            -- Install headers
            os.cp("include/QtLucide", path.join(target:installdir(), "include"))

            -- Install library
            os.cp(target:targetfile(), path.join(target:installdir(), "lib"))

            -- Install package config (simplified version)
            local config_dir = path.join(target:installdir(), "lib", "cmake", "QtLucide")
            os.mkdir(config_dir)

            -- Create a simple config file
            local lib_ext = is_plat("windows") and ".lib" or ".a"
            local lib_name = is_plat("windows") and "QtLucide" .. lib_ext or "libQtLucide" .. lib_ext
            local config_content = string.format([[
# QtLucide CMake configuration file (generated by xmake)
include(CMakeFindDependencyMacro)
find_dependency(Qt6 REQUIRED COMPONENTS Core Gui Widgets Svg)

if(NOT TARGET QtLucide::QtLucide)
    add_library(QtLucide::QtLucide STATIC IMPORTED)
    set_target_properties(QtLucide::QtLucide PROPERTIES
        IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/../../../lib/%s"
        INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/../../../include"
        INTERFACE_LINK_LIBRARIES "Qt6::Core;Qt6::Gui;Qt6::Widgets;Qt6::Svg"
    )
endif()
]], lib_name)
            io.writefile(path.join(config_dir, "QtLucideConfig.cmake"), config_content)
        end)
    end
target_end()

-- Examples
if has_config("examples") then
    -- Basic usage example
    target("QtLucideExample")
        set_kind("binary")
        add_rules("qt.widgetapp")
        add_frameworks("QtCore", "QtGui", "QtWidgets")

        add_files("examples/basic_usage/main.cpp")
        add_files("examples/basic_usage/MainWindow.cpp")
        add_files("examples/basic_usage/MainWindow.h")

        add_deps("QtLucide")
        add_includedirs("include")

        -- Set as GUI application
        if is_plat("macosx") then
            add_ldflags("-Wl,-rpath,@executable_path/../Frameworks", {force = true})
        end
    target_end()

    -- Gallery example - Complete QtLucide Gallery Application
    target("QtLucideGallery")
        set_kind("binary")
        add_rules("qt.widgetapp")
        add_frameworks("QtCore", "QtGui", "QtWidgets", "QtSvg", "QtConcurrent", "QtNetwork")

        -- Gallery source files
        -- Configuration
        add_headerfiles("examples/gallery/src/config/LayoutConfig.h")

        -- Core functionality
        add_headerfiles("examples/gallery/src/core/GalleryTypes.h")
        -- Note: BatchExportWorker.h is header-only and included via BatchExportManager.cpp
        -- Do not add it here to avoid MOC duplicate definition errors
        add_files("examples/gallery/src/core/BatchExportManager.h")
        add_files("examples/gallery/src/core/BatchExportManager.cpp")
        add_files("examples/gallery/src/core/ExportProgressWidget.h")
        add_files("examples/gallery/src/core/ExportProgressWidget.cpp")

        -- Core managers
        add_files("examples/gallery/src/core/managers/ContentManager.h")
        add_files("examples/gallery/src/core/managers/ContentManager.cpp")
        add_files("examples/gallery/src/core/managers/IconMetadataManager.h")
        add_files("examples/gallery/src/core/managers/IconMetadataManager.cpp")
        add_files("examples/gallery/src/core/managers/ManagerStubs.h")
        add_files("examples/gallery/src/core/managers/ManagerStubs.cpp")
        add_files("examples/gallery/src/core/managers/FavoritesManager.h")
        add_files("examples/gallery/src/core/managers/FavoritesManager.cpp")

        -- Core models
        add_files("examples/gallery/src/core/models/IconItem.h")
        add_files("examples/gallery/src/core/models/IconItem.cpp")

        -- Core utils
        add_files("examples/gallery/src/core/utils/GalleryLogger.h")
        add_files("examples/gallery/src/core/utils/GalleryLogger.cpp")
        add_files("examples/gallery/src/core/utils/ErrorHandler.h")
        add_files("examples/gallery/src/core/utils/ErrorHandler.cpp")

        -- UI themes
        add_files("examples/gallery/src/ui/themes/ThemeManager.h")
        add_files("examples/gallery/src/ui/themes/ThemeManager.cpp")

        -- UI layouts
        add_files("examples/gallery/src/ui/layouts/ResponsiveLayoutManager.h")
        add_files("examples/gallery/src/ui/layouts/ResponsiveLayoutManager.cpp")

        -- UI controllers
        add_files("examples/gallery/src/ui/controllers/SearchController.h")
        add_files("examples/gallery/src/ui/controllers/SearchController.cpp")
        add_files("examples/gallery/src/ui/controllers/PerformanceMonitor.h")
        add_files("examples/gallery/src/ui/controllers/PerformanceMonitor.cpp")

        -- UI widgets - grids
        add_files("examples/gallery/src/ui/widgets/grids/IconGridWidget.h")
        add_files("examples/gallery/src/ui/widgets/grids/IconGridWidget.cpp")
        add_files("examples/gallery/src/ui/widgets/grids/IconThumbnailGridWidget.h")
        add_files("examples/gallery/src/ui/widgets/grids/IconThumbnailGridWidget.cpp")

        -- UI widgets - search
        add_files("examples/gallery/src/ui/widgets/search/SearchWidget.h")
        add_files("examples/gallery/src/ui/widgets/search/SearchWidget.cpp")
        add_files("examples/gallery/src/ui/widgets/search/IconSearchWidget.h")
        add_files("examples/gallery/src/ui/widgets/search/IconSearchWidget.cpp")
        add_files("examples/gallery/src/ui/widgets/search/CategoryFilterWidget.h")
        add_files("examples/gallery/src/ui/widgets/search/CategoryFilterWidget.cpp")

        -- UI widgets - panels
        add_files("examples/gallery/src/ui/widgets/panels/CategorySidebarWidget.h")
        add_files("examples/gallery/src/ui/widgets/panels/CategorySidebarWidget.cpp")
        add_files("examples/gallery/src/ui/widgets/panels/IconDetailsPanel.h")
        add_files("examples/gallery/src/ui/widgets/panels/IconDetailsPanel.cpp")
        add_files("examples/gallery/src/ui/widgets/panels/FileBrowserWidget.h")
        add_files("examples/gallery/src/ui/widgets/panels/FileBrowserWidget.cpp")

        -- UI widgets - viewers
        add_files("examples/gallery/src/ui/widgets/viewers/ImageViewerWidget.h")
        add_files("examples/gallery/src/ui/widgets/viewers/ImageViewerWidget.cpp")

        -- UI dialogs
        add_files("examples/gallery/src/ui/dialogs/ExportDialog.h")
        add_files("examples/gallery/src/ui/dialogs/ExportDialog.cpp")
        add_files("examples/gallery/src/ui/dialogs/ImportDialog.h")
        add_files("examples/gallery/src/ui/dialogs/ImportDialog.cpp")
        add_files("examples/gallery/src/ui/dialogs/IconExportDialog.h")
        add_files("examples/gallery/src/ui/dialogs/IconExportDialog.cpp")
        add_files("examples/gallery/src/ui/dialogs/PreferencesDialog.h")
        add_files("examples/gallery/src/ui/dialogs/PreferencesDialog.cpp")

        -- UI windows
        add_files("examples/gallery/src/ui/windows/GalleryMainWindow.h")
        add_files("examples/gallery/src/ui/windows/GalleryMainWindow.cpp")

        -- Main application
        add_files("examples/gallery/src/main/main.cpp")

        -- Gallery include directories
        add_includedirs("include")
        add_includedirs("examples/gallery/src")
        add_includedirs("examples/gallery/src/core")
        add_includedirs("examples/gallery/src/core/utils")
        add_includedirs("examples/gallery/src/core/managers")
        add_includedirs("examples/gallery/src/core/models")
        add_includedirs("examples/gallery/src/ui")
        add_includedirs("examples/gallery/src/ui/themes")
        add_includedirs("examples/gallery/src/ui/controllers")
        add_includedirs("examples/gallery/src/ui/widgets")
        add_includedirs("examples/gallery/src/ui/widgets/grids")
        add_includedirs("examples/gallery/src/ui/widgets/panels")
        add_includedirs("examples/gallery/src/ui/widgets/search")
        add_includedirs("examples/gallery/src/ui/widgets/viewers")
        add_includedirs("examples/gallery/src/ui/dialogs")
        add_includedirs("examples/gallery/src/ui/layouts")
        add_includedirs("examples/gallery/src/ui/windows")
        add_includedirs("examples/gallery/src/main")
        add_includedirs("examples/gallery/src/config")

        -- Link QtLucide
        add_deps("QtLucide")

        -- Set output name
        set_basename("QtLucideGallery")

        -- Set as GUI application
        if is_plat("macosx") then
            add_ldflags("-Wl,-rpath,@executable_path/../Frameworks", {force = true})
        end

        -- Installation
        on_install(function (target)
            os.cp(target:targetfile(), path.join(target:installdir(), "bin"))
        end)
    target_end()
end

-- Tests
if has_config("tests") then
    -- Core unit tests
    target("QtLucideCoreTests")
        set_kind("binary")
        add_rules("qt.console")
        add_frameworks("QtCore", "QtGui", "QtWidgets", "QtSvg", "QtTest")

        -- Test sources - unit/core tests
        add_files("tests/main.cpp")
        add_files("tests/unit/core/test_qtlucide.cpp")
        add_files("tests/unit/core/test_icon_engine.cpp")
        add_files("tests/unit/core/test_icon_painter.cpp")
        add_files("tests/unit/core/test_icon_loading.cpp")
        add_files("tests/unit/core/test_svg_rendering.cpp")
        add_files("tests/unit/core/test_error_handling.cpp")
        add_files("tests/unit/core/test_memory_management.cpp")
        add_files("tests/unit/core/test_boundary_conditions.cpp")
        add_files("tests/unit/core/test_thread_safety.cpp")

        -- Test headers that need MOC
        add_files("tests/unit/core/test_qtlucide.h")
        add_files("tests/unit/core/test_icon_engine.h")
        add_files("tests/unit/core/test_icon_painter.h")
        add_files("tests/unit/core/test_icon_loading.h")
        add_files("tests/unit/core/test_svg_rendering.h")
        add_files("tests/unit/core/test_error_handling.h")
        add_files("tests/unit/core/test_memory_management.h")
        add_files("tests/unit/core/test_boundary_conditions.h")
        add_files("tests/unit/core/test_thread_safety.h")

        add_deps("QtLucide")
        add_includedirs("include")
        add_includedirs("tests/unit/core")

        -- Add test runner
        on_run(function (target)
            os.exec(target:targetfile())
        end)
    target_end()
end

-- Global installation rules
on_install(function (target)
    print("QtLucide installation completed!")
end)

-- Custom tasks
task("clean-resources")
    set_menu {
        usage = "xmake clean-resources",
        description = "Clean generated resource files",
    }
    on_run(function ()
        local files_to_clean = {
            "resources/icons/lucide_icons.qrc",
            "resources/icons/metadata/icons.json",
            "include/QtLucide/QtLucideEnums.h",
            "include/QtLucide/QtLucideStrings.h"
        }

        for _, file in ipairs(files_to_clean) do
            if os.isfile(file) then
                os.rm(file)
                print("Removed: " .. file)
            end
        end
        print("Resource cleanup completed!")
    end)
task_end()

task("generate-resources")
    set_menu {
        usage = "xmake generate-resources",
        description = "Generate resource files from SVG icons",
    }
    on_run(function ()
        local python_cmd = "python"
        if os.host() == "windows" then
            python_cmd = "python.exe"
        end
        local build_script = path.join(os.projectdir(), "tools", "build_resources.py")
        local project_dir = os.projectdir()

        print("Generating QtLucide resources...")
        os.execv(python_cmd, {build_script, project_dir})
        print("Resource generation completed!")
    end)
task_end()
